spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/mogong2?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    password: allrounded-mogong-1234

logging.level:
  org.hibernate.SQL: debug
  hufs.team.mogong: debug
